# Generated by Django 5.1.1 on 2024-11-12 14:22

import nexus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('nexus', '0011_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='expires_at',
            field=models.DateTimeField(
                default=nexus.models.Story.default_expiration_time),
        ),
    ]
