name: SonarCloudScan

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java (SonarCloud requires Java)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Cache SonarCloud dependencies
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # Step 4: Run the SonarCloud scanner
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=nexus \
            -Dsonar.organization=momina-asif \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io
